from enum import IntEnum

class PKT_TYPE(IntEnum):
    HANDSHAKE_REQUEST = 0x1
    HANDSHAKE_RESPONSE = 0x2
    EXTENDED_AUTH_MSG = 0x3
    TUNNEL_CREATE = 0x4
    TUNNEL_RESPONSE = 0x5
    TUNNEL_AUTH = 0x6
    TUNNEL_AUTH_RESPONSE = 0x7
    CHANNEL_CREATE = 0x8
    CHANNEL_RESPONSE = 0x9
    DATA = 0xA
    SERVICE_MESSAGE = 0xB
    REAUTH_MESSAGE = 0xC
    KEEPALIVE = 0xD
    CLOSE_CHANNEL = 0x10
    CLOSE_CHANNEL_RESPONSE = 0x11

class HTTP_TUNNEL_RESPONSE_FIELD(IntEnum):
    TUNNEL_ID = 0x1
    CAPS = 0x2
    SOH_REQ = 0x4
    CONSENT_MSG = 0x10

class HTTP_TUNNEL_AUTH_RESPONSE_FIELD(IntEnum):
    REDIR_FLAGS = 0x1
    IDLE_TIMEOUT = 0x2
    SOH_RESPONSE = 0x4
